apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-sa1
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-watcher1
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "delete"
      - "watch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-ra-event-watcher1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-watcher1
subjects:
  - kind: ServiceAccount
    name: events-sa1
    namespace: default