# This is a simple example that creates a source and sends events to a function.

# The namespace the example lives in.

apiVersion: v1
kind: Namespace
metadata:
  name: knative-debug1

---
# K8s Deployment that simply writes input requests to its log.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fn
  namespace: knative-debug1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fn
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: fn
    spec:
      containers:
        - name: user-container
          # This corresponds to
          # https://github.com/knative/eventing-sources/blob/v0.2.1/cmd/message_dumper/dumper.go.
          image: gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/message_dumper@sha256:ab5391755f11a5821e7263686564b3c3cd5348522f5b31509963afb269ddcd63
          ports:
            - containerPort: 8080

---

# K8s Service which points at the Deployment below.

apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: knative-debug1
spec:
  selector:
    app: fn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
