# The event source.

apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KubernetesEventSource
metadata:
  name: src
  namespace: knative-debug1
spec:
  namespace: knative-debug1
  serviceAccountName: service-account
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: chan

---


# The Subscription to the Channel.

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: sub
  namespace: knative-debug1
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: chan
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: svc



# Everything after this is just structure for the above.

---

# K8s Service Account that runs `src`'s container.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: knative-debug1

---

# The permissions that `src` needs.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: event-watcher
  namespace: knative-debug1
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch

---

# Give `src`'s service account the necessary permissions.

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: k8s-ra-event-watcher
  namespace: knative-debug1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: event-watcher
subjects:
  - kind: ServiceAccount
    name: service-account
    namespace: knative-debug
